version: '3.8'

services:
  blogapi:
    container_name: blogapi-prd
    build:
      context: .
      dockerfile: ./src/BlogApi.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ENVIRONMENT_VARIABLE_FRONT_END_URL=https://www.ozos.com.br
      - ENVIRONMENT_VARIABLE_BACK_END_URL=https://api.ozos.com.br
      - DOTNET_RUNNING_IN_CONTAINER=true
      - VIRTUAL_HOST=api.ozos.com.br
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.ozos.com.br
      - LETSENCRYPT_EMAIL=gabrielc.machado@hotmail.com
      - ConnectionStrings__DATA_DATABASE=Host=ep-silent-fog-a4x2e7sc-pooler.us-east-1.aws.neon.tech;Database=BlogApi;Username=BlogApi_owner;Password=npg_xzwdmT5g7RjP;SSL Mode=Require;Trust Server Certificate=true
      - ConnectionStrings__IDENTITY_DATABASE=Host=ep-silent-fog-a4x2e7sc-pooler.us-east-1.aws.neon.tech;Database=BlogApi;Username=BlogApi_owner;Password=npg_xzwdmT5g7RjP;SSL Mode=Require;Trust Server Certificate=true
    depends_on:
      - mariadb
    networks:
      - nginx-net
    restart: always
    volumes:
      - blogapi-migrations:/app/migrations

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-blogapi
    restart: always
    environment:
      MARIADB_DATABASE: blogapi_db
      MARIADB_USER: bloguser
      MARIADB_PASSWORD: blogpass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - blogapi-mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Porta explicitamente mapeada
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true

volumes:
  blogapi-mariadb-data:
  blogapi-migrations:

